# Generated by Django 4.1.6 on 2023-02-08 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profiles/')),
                ('favorite_team', models.CharField(choices=[('ATL', 'ATL'), ('BKN', 'BKN'), ('BOS', 'BOS'), ('CHA', 'CHA'), ('CHI', 'CHI'), ('CLE', 'CLE'), ('DAL', 'DAL'), ('DEN', 'DEN'), ('DET', 'DET'), ('GSW', 'GSW'), ('HOU', 'HOU'), ('IND', 'IND'), ('LAC', 'LAC'), ('LAL', 'LAL'), ('MEM', 'MEM'), ('MIA', 'MIA'), ('MIL', 'MIL'), ('MIN', 'MIN'), ('NBA', 'NBA'), ('NOP', 'NOP'), ('NYK', 'NYK'), ('OKC', 'OKC'), ('ORL', 'ORL'), ('PHI', 'PHI'), ('PHX', 'PHX'), ('POR', 'POR'), ('SAC', 'SAC'), ('SAS', 'SAS'), ('TOR', 'TOR'), ('UTA', 'UTA'), ('WAS', 'WAS')], default='NBA', max_length=31)),
                ('right_handed', models.BooleanField(default=True)),
                ('correct_guesses', models.IntegerField(null=True)),
                ('incorrect_guesses', models.IntegerField(null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
