# Generated by Django 4.1.6 on 2023-02-08 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=255, null=True)),
                ('away_team', models.CharField(max_length=255, null=True)),
                ('home_team_score', models.IntegerField(default=0, null=True)),
                ('away_team_score', models.IntegerField(default=0, null=True)),
                ('winning_team', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('user_pick', models.CharField(max_length=255)),
                ('opponent', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('challenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
